### ISSUE TITLE
Assignment 5, Exploratory and Expository Figures

### ISSUE THREAD

**Issue by CristianSwift** [CristianSwift/Assignment-5#1]
In this assignment I used a dataframe that has Siscowet characteristics of Lake Trout captured at four locations in Michigan waters of Lake Superior. First I made an exploratory figure investigating the relationship between age and length. Then I made an expository figure of the exploratory figure that had a linear regression line.

**Comment by mdscheuerell** [comment]
Thanks, Cristian. Note, though, that simply adding a regression line to a plot does not take it from exploratory to expository. The latter is akin to something you'd see published in a journal article.
